# Update with `pre-commit autoupdate --freeze` which
# pins all repos using commit hashes, not mutable references
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: check-yaml
      - id: forbid-submodules
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
        exclude: ^ruby-3\.0/0001-ruby-3\.0\.6-openssl-patch\.patch$
  - repo: https://github.com/chainguard-dev/yam
    rev: fdb5b8c7c09513ca1ed6a88dba5951e4e52be1a7
    hooks:
      - id: yam
        files: ^[^\./]+\.yaml$
  - repo: https://github.com/chainguard-dev/pre-commit-hooks
    rev: c1d84c35a1824a9e1a4d2395ffa3e81bf77dd8f0
    hooks:
      - id: shellcheck-run-steps
        files: ^[^\./]+\.yaml$
        args: [--, -S, error]
