package:
  name: cgal
  version: 6.0.1
  epoch: 2
  description: Efficient and reliable geometric algorithms as C++ library
  copyright:
    - license: GPL-3.0-or-later custom

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cmake

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 50cfbde3b84dbeae8338268db2d78fe4fcb522de
      repository: https://github.com/CGAL/cgal
      tag: v${{package.version}}
      destination: CGAL-${{package.version}}

  - working-directory: /home/build
    pipeline:
      - runs: cmake -B build -S CGAL-${{package.version}} -W no-dev -DCMAKE_INSTALL_PREFIX=/usr
      - runs: DESTDIR="${{targets.contextdir}}" cmake --install build

subpackages:
  - name: cgal-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - cgal
    description: cgal dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

  - name: cgal-doc
    pipeline:
      - uses: split/manpages
    description: cgal manpages
    test:
      pipeline:
        - uses: test/docs
