package:
  name: cgal
  version: 6.0.1
  epoch: 2
  description: Efficient and reliable geometric algorithms as C++ library
  copyright:
    - license: GPL-3.0-or-later
    - license: BSL-1.0
    - license: LGPL-3.0-or-later
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - cmake
      - eigen-dev
      - mpfr-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 50cfbde3b84dbeae8338268db2d78fe4fcb522de
      repository: https://github.com/CGAL/cgal
      tag: v${{package.version}}
      destination: CGAL-${{package.version}}

  - working-directory: /home/build
    pipeline:
      - runs: cmake -B build -S CGAL-${{package.version}} -W no-dev -DCMAKE_INSTALL_PREFIX=/usr
      - runs: DESTDIR="${{targets.contextdir}}" cmake --install build
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/
          mv ${{targets.contextdir}}/usr/lib64 ${{targets.contextdir}}/usr/lib

  - runs: rm -rf ${{targets.contextdir}}/usr/share/doc/ # docs don't have a OSI approved license.

  - runs: rm -rf ${{targets.contextdir}}/usr/share/man/ # docs don't have a OSI approved license.

  - uses: strip

subpackages:
  - name: cgal-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - cgal
    description: cgal dev
    test:
      pipeline:
        - uses: test/pkgconf
        - runs: stat /usr/include/CGAL/*.h

update:
  enabled: true
  git:
    strip-prefix: v
