package:
  name: mamba-package
  version: 2.0.4
  epoch: 0
  description: Cross-Platform Package Manager
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - ccache
      - clang
      - cli11
      - cmake
      - curl-dev
      - doctest
      - fmt-dev
      - libarchive-dev
      - libmamba-dev
      - libsolv-dev
      - make
      - nlohmann-json
      - openssf-compiler-options
      - openssl-dev
      - reproc
      - reproc++
      - samurai
      - simdjson-dev
      - spdlog-dev
      - tl-expected
      - yaml-cpp-dev
      - zstd-dev
      - zstd-static
  environment:
    CXXFLAGS: "-fPIC"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: c809abcba67fa3a94e205552ac1a6388c1736934
      repository: https://github.com/mamba-org/mamba
      tag: mamba-${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DBUILD_LIBMAMBA="OFF" \
        -DBUILD_SHARED="ON" \
        -DBUILD_LIBMAMBAPY="OFF" \
        -DBUILD_MICROMAMBA="OFF" \
        -DBUILD_MAMBA_PACKAGE="ON" \
        -DCMAKE_BUILD_TYPE=Release

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: true
  github:
    identifier: mamba-org/mamba
    strip-prefix: mamba-
    tag-filter-prefix: mamba-

test:
  environment:
    contents:
      packages:
        - mamba-package
  pipeline:
    - runs: |
        mamba-package --help
        
