package:
  name: py3-graph-tool
  version: 2.97
  epoch: 0
  description: graph-tool is an efficient Python module for manipulation and statistical analysis of graphs (a.k.a. networks).
  copyright:
    - license: GPL-3.0-only

vars:
  pypi-package: graph-tool
  import: graph_tool

data:
  # TODO: add other supported versions
  - name: py-versions
    items:
      3.13:

environment:
  contents:
    packages:
      - autoconf
      - automake
      - bash
      - boost-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cairo-dev
      - cairomm-dev
      - cgal-dev
      - eigen-dev
      - expat-dev
      - freetype-dev
      - gmp-dev
      - libsigcplusplus-dev
      - libtool
      - mpfr-dev
      - pkgconf-dev
      - py3.13-cairo
      - py3.13-numpy
      - py3.13-build-base-dev
      - sparsehash-dev
      - zlib-dev
  environment:
    CAIROMM_LIBS: "/usr/lib/cairomm-1.16"
    CAIROMM_CFLAGS: "-Wno-error"

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.skewed.de/count0/graph-tool
      tag: release-${{package.version}}
      expected-commit: cd15650ec9fb6807b4536b523a059354f231fcb1

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provides:
        - graph-tool=${{package.full-version}}
      runtime:
        - py${{range.key}}-numpy
        - py${{range.key}}-scipy
    pipeline:
      - runs: |
          ./autogen.sh
          CXXFLAGS=${CXXFLAGS/-Wp,-D_GLIBCXX_ASSERTIONS/}
          export CXXFLAGS="$CXXFLAGS -O3"

      - runs: |
          cp -r /usr/include/cairo/* /usr/lib/python${{range.key}}/site-packages/cairo/include/
          cp -r /usr/include/freetype2/* /usr/lib/python${{range.key}}/site-packages/cairo/include/

      - uses: autoconf/configure
        with:
          opts: |
            --enable-openmp \
            --includedir=/usr/lib/cairomm-1.16 \
            PYTHON=python${{range.key}}

      - runs: |
          ln -s /usr/lib/cairomm-1.16/include/cairommconfig.h /usr/include/cairommconfig.h
          ln -s /usr/include/cairomm-1.16/cairomm/ /usr/include/cairomm
          ln -s /usr/lib/sigc++-3.0/include/sigc++config.h /usr/include/sigc++config.h
          ln -s /usr/include/sigc++-3.0/sigc++/ /usr/include/sigc++
          export CPPFLAGS="$CPPFLAGS -I/usr/lib/cairomm-1.16/include -I/usr/include/cairomm-1.16/cairomm/ -I/usr/include/sigc++-3.0/sigc++/"
          make -C . -j16 V=1

      - uses: autoconf/make-install

      - uses: strip
    test:
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: ${{vars.import}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        # TODO: Add other python versions
        - py3.13-${{vars.pypi-package}}
    test:
      pipeline:
        - uses: python/import
          with:
            python: python3.13
            import: ${{vars.import}}

  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.contextdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.contextdir}}"/usr/share/
    description: ${{package.name}} manpages
    test:
      pipeline:
        - uses: test/docs

  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

update:
  enabled: true
  git:
    strip-prefix: release-

test:
  pipeline:
    - uses: test/emptypackage
